package org.itmo;

import java.util.*;
import java.util.concurrent.*;
import java.util.stream.IntStream;

class Graph {
    private final int V;
    private final ArrayList<Integer>[] adjList;

    Graph(int vertices) {
        this.V = vertices;
        adjList = new ArrayList[vertices];
        for (int i = 0; i < vertices; ++i) {
            adjList[i] = new ArrayList<>();
        }
    }

    void addEdge(int src, int dest) {
        if (!adjList[src].contains(dest)) {
            adjList[src].add(dest);
        }
    }

    //Generated by ChatGPT
    void bfs(int startVertex) {
        boolean[] visited = new boolean[V];

        LinkedList<Integer> queue = new LinkedList<>();

        visited[startVertex] = true;
        queue.add(startVertex);

        while (!queue.isEmpty()) {
            startVertex = queue.poll();

            for (int n : adjList[startVertex]) {
                if (!visited[n]) {
                    visited[n] = true;
                    queue.add(n);
                }
            }
        }
    }

    void parallelStreamBfs(int startVertex) {
        boolean[] visited = new boolean[V];

        ConcurrentLinkedQueue<Integer> currentQueue = new ConcurrentLinkedQueue<>();
        ConcurrentLinkedQueue<Integer> newQueue = new ConcurrentLinkedQueue<>();

        visited[startVertex] = true;
        currentQueue.add(startVertex);

        while (!currentQueue.isEmpty()) {
            ConcurrentLinkedQueue<Integer> finalNewQueue = newQueue;
            currentQueue.stream().parallel()
                    .forEach(node -> adjList[node].stream()
                            .filter(nextNode -> !visited[nextNode])
                            .forEach(nextNode -> {
                                visited[nextNode] = true;
                                finalNewQueue.add(nextNode);
                            }));
            currentQueue = finalNewQueue;
            newQueue = new ConcurrentLinkedQueue<>();
        }
    }

    void forkJoinPoolBfs(int startVertex) {
        boolean[] visited = new boolean[V];

        ConcurrentLinkedQueue<Integer> queue = new ConcurrentLinkedQueue<>();

        try (ForkJoinPool pool = new ForkJoinPool()) {

            visited[startVertex] = true;
            queue.add(startVertex);

            while (!queue.isEmpty()) {
                ConcurrentLinkedQueue<Integer> newQueue = new ConcurrentLinkedQueue<>();
                pool.invoke(new BFSForkJoinTask(visited, queue.spliterator(), newQueue));
                queue = newQueue;
            }
        }
    }

    private static final Long SERIAL_SIZE = 100L;

    private class BFSForkJoinTask extends RecursiveTask<Collection<Integer>> {

        private final boolean[] visited;
        private final Spliterator<Integer> currentNodes;
        private final Collection<Integer> collector;

        public BFSForkJoinTask(boolean[] visited, Spliterator<Integer> currentNodes, Collection<Integer> collector) {
            this.visited = visited;
            this.currentNodes = currentNodes;
            this.collector = collector;
        }

        @Override
        protected Collection<Integer> compute() {
            if (currentNodes.estimateSize() < SERIAL_SIZE) {
                syncCompute();
                return collector;
            }
            Spliterator<Integer> splitCurrentNodes = currentNodes.trySplit();
            if (splitCurrentNodes != null) {
                BFSForkJoinTask task1 = new BFSForkJoinTask(visited, currentNodes, collector);
                BFSForkJoinTask task2 = new BFSForkJoinTask(visited, splitCurrentNodes, collector);
                task1.fork();
                task2.fork();
                task1.join();
                task2.join();
            } else {
                syncCompute();
            }
            return collector;
        }

        private void syncCompute() {
            currentNodes.forEachRemaining(node -> adjList[node]
                    .forEach(newNode -> {
                                if (!visited[newNode]) {
                                    visited[newNode] = true;
                                    collector.add(newNode);
                                }
                            }
                    )
            );
        }

    }

    void fixedThreadPoolBfs(int startVertex) {
        executorServiceBfs(Executors.newFixedThreadPool(16), startVertex);
    }

    void forkJoinPoolExecutorBfs(int startVertex) {
        executorServiceBfs(new ForkJoinPool(), startVertex);
    }

    void virtualPoolExecutorBfs(int startVertex) {
        executorServiceBfs(Executors.newVirtualThreadPerTaskExecutor(), startVertex);
    }

    private static final int FIXED_THREAD_POOL_SERIAL_SIZE = 100;

    private void executorServiceBfs(ExecutorService executorService, int startVertex) {
        boolean[] visited = new boolean[V];

        List<Integer> nodes = new ArrayList<>();


        visited[startVertex] = true;
        nodes.add(startVertex);

        while (!nodes.isEmpty()) {

            int partCount = Math.max(1, Math.min(32, nodes.size() / FIXED_THREAD_POOL_SERIAL_SIZE));

            ConcurrentLinkedQueue<Integer> collector = new ConcurrentLinkedQueue<>();
            List<Integer> finalNodes = nodes;
            var callableList = IntStream.range(0, partCount).mapToObj((part) ->
                    (Callable<Collection<Integer>>) (() -> runExecutedTask(visited, finalNodes, collector, part, partCount))
            ).toList();

            try {
                executorService.invokeAll(callableList);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            nodes = new ArrayList<>(collector);
        }
    }

    private <T extends Collection<Integer>> T runExecutedTask(boolean[] visited, List<Integer> nodes, T collector, int part, int totalPartCount) {
        int start = (int) ((long) nodes.size() * part / totalPartCount);
        int end = (int) ((long) nodes.size() * (part + 1) / totalPartCount);
        for (int i = start; i < end; i++) {
            int node = nodes.get(i);
            adjList[node].forEach(newNode -> {
                        if (!visited[newNode]) {
                            visited[newNode] = true;
                            collector.add(newNode);
                        }
                    }
            );
        }
        return collector;
    }

}
